version: '3.8'

services:
  main:
    depends_on:
      influxdb:
        condition: service_healthy
    build:
      context: .

    environment:
      - PYTHONUNBUFFERED=1
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_BUCKET=primary
      - INFLUXDB_ORGANIZATION=primary
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - SYMBOLS=${SYMBOLS}

  influxdb:
    image: bitnami/influxdb:2.2.0
    healthcheck:
      test: curl --fail -s http://localhost:8086 || exit 1
      interval: 5s
      timeout: 90s
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb_data:/bitnami/influxdb
    environment:
      - INFLUXDB_ADMIN_USER_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_ADMIN_USER_TOKEN=${INFLUXDB_TOKEN}
