version: '3.8'

services:
  main:
    depends_on:
      influxdb:
        condition: service_healthy
    build:
      context: .

    environment:
      - PYTHONUNBUFFERED=1
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_BUCKET=primary
      - INFLUXDB_ORGANIZATION=primary
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - SYMBOLS=${SYMBOLS}

  influxdb:
    image: influxdb:2.2.0-alpine
    healthcheck:
      test: curl --fail -s http://localhost:8086 || exit 1
      start_period: 90s
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=primary
      - DOCKER_INFLUXDB_INIT_BUCKET=primary
      - DOCKER_INFLUXDB_INIT_RETENTION=1w
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
